export const SIGN_OUT = 'SIGN_OUT'
export const SIGN_IN = 'SIGN_IN'
export const SET_USER = 'SET_USER'
export const SET_RESIDENTS = 'SET_RESIDENTS'
export const ADD_EVENT = 'ADD_EVENT'
export const UPDATE_BOARD = 'UPDATE_BOARD'
export const SET_TRACKS = 'SET_TRACKS'
